pub mod fieldarith;
pub mod fuzz;
pub mod hfile;
pub mod hts_endian;
pub mod pileup;
pub mod pileup_mod;
#[path = "plugins-dlhts.rs"]
pub mod plugins_dlhts;
pub mod sam;
#[path = "test-bcf_set_variant_type.rs"]
pub mod test_bcf_set_variant_type;
#[path = "test-bcf-sr.rs"]
pub mod test_bcf_sr;
pub mod test_bgzf;
pub mod test_expr;
pub mod test_faidx;
pub mod test_hfile_libcurl;
pub mod test_index;
pub mod test_introspection;
pub mod test_kfunc;
pub mod test_khash;
pub mod test_kstring;
pub mod test_mod;
pub mod test_nibbles;
#[path = "test-parse-reg.rs"]
pub mod test_parse_reg;
pub mod test_realn;
#[path = "test-regidx.rs"]
pub mod test_regidx;
pub mod test_str2int;
pub mod test_time_funcs;
#[path = "test-vcf-api.rs"]
pub mod test_vcf_api;
#[path = "test-vcf-sweep.rs"]
pub mod test_vcf_sweep;
pub mod test_view;
pub mod thrash_threads1;
pub mod thrash_threads2;
pub mod thrash_threads3;
pub mod thrash_threads4;
pub mod thrash_threads5;
pub mod thrash_threads6;
pub mod thrash_threads7;
