[package]
name = "htslib-mini-rs"
version = "0.0.1"
edition = "2021"
license = "MIT OR BSD-3-Clause"
description = "Rust translation of HTSlib"
readme = "README.md"

[lib]
name = "htslib_mini_rs"
path = "src/lib.rs"

[dependencies]
flate2 = "1"
hts-sys = "2.2.0"
libc = "0.2"
tracehash-rs = "0.2.0"
xz2 = "0.1"

[dev-dependencies]
noodles = { version = "0.109.0", features = ["bgzf"] }
