// original: print_usage (htslib/samples/cram.c:37)
pub unsafe fn samples_cram_c_37_print_usage(fp: *mut libc::FILE) {
    libc::fprintf(
        fp,
        c"Usage: cram infile reffile outdir\nDumps the input file alignments in cram format in given directory\n1.cram has external reference\n2.cram has reference embedded\n3.cram has autogenerated reference\n4.cram has no reference data in it\n".as_ptr(),
    );
}

// original: main (htslib/samples/cram.c:53)
pub unsafe fn samples_cram_c_53_main() {
    todo!("translate HTSlib main from htslib/samples/cram.c:53");
}
