use crate::htslib_rs::{hts, sam};
use std::io::Write;

// original: print_usage (htslib/samples/cram.c:37)
pub unsafe fn samples_cram_c_37_print_usage() {
    eprint!(
        "Usage: cram infile reffile outdir\nDumps the input file alignments in cram format in given directory\n1.cram has external reference\n2.cram has reference embedded\n3.cram has autogenerated reference\n4.cram has no reference data in it\n"
    );
}

// original: main (htslib/samples/cram.c:53)
pub unsafe fn samples_cram_c_53_main(args: &[&[u8]]) -> i32 {
    let mut __out = std::io::stdout();
    let mut ret = 1;
    let mut infile = std::ptr::null_mut();
    let mut outfile1 = std::ptr::null_mut();
    let mut outfile2 = std::ptr::null_mut();
    let mut outfile3 = std::ptr::null_mut();
    let mut outfile4 = std::ptr::null_mut();
    let mut in_samhdr = std::ptr::null_mut();
    let mut bamdata = std::ptr::null_mut();
    let mut fmt1: hts::htsFormat = std::mem::zeroed();
    let mut fmt2: hts::htsFormat = std::mem::zeroed();
    let mut fmt3: hts::htsFormat = std::mem::zeroed();
    let mut fmt4: hts::htsFormat = std::mem::zeroed();

    if args.len() != 4 {
        samples_cram_c_37_print_usage();
        return ret;
    }
    let inname = args[1];
    // argv entries are NUL-terminated C strings; use bytes up to the first NUL.
    let reffile = &args[2][..args[2].iter().position(|&b| b == 0).unwrap_or(args[2].len())];
    let outdir = &args[3][..args[3].iter().position(|&b| b == 0).unwrap_or(args[3].len())];

    // NUL-terminated byte buffers passed to still-raw C-ABI API functions.
    let mut reffmt1 = b"cram,reference=".to_vec();
    reffmt1.extend_from_slice(reffile);
    reffmt1.push(0);
    let mut reffmt2 = b"cram,embed_ref=1,reference=".to_vec();
    reffmt2.extend_from_slice(reffile);
    reffmt2.push(0);

    let mut file1 = outdir.to_vec();
    file1.extend_from_slice(b"/1.cram\0");
    let mut file2 = outdir.to_vec();
    file2.extend_from_slice(b"/2.cram\0");
    let mut file3 = outdir.to_vec();
    file3.extend_from_slice(b"/3.cram\0");
    let mut file4 = outdir.to_vec();
    file4.extend_from_slice(b"/4.cram\0");

    let mut inname_z = inname.to_vec();
    inname_z.push(0);

    if hts::hts_parse_format(&mut fmt1, reffmt1.as_ptr().cast()) == -1
        || hts::hts_parse_format(&mut fmt2, reffmt2.as_ptr().cast()) == -1
        || hts::hts_parse_format(&mut fmt3, c"cram,embed_ref=2".as_ptr()) == -1
        || hts::hts_parse_format(&mut fmt4, c"cram,no_ref=1".as_ptr()) == -1
    {
        write!(__out, "Failed to set output option\n").unwrap();
    } else {
        bamdata = sam::bam_init1();
        if bamdata.is_null() {
            write!(__out, "Failed to initialize bamdata\n").unwrap();
        } else {
            infile = hts::hts_open(inname_z.as_ptr().cast(), c"r".as_ptr());
            if infile.is_null() {
                write!(__out, "Could not open {}\n", String::from_utf8_lossy(inname)).unwrap();
            } else {
                outfile1 = hts::hts_open_format(file1.as_ptr().cast(), c"wc".as_ptr(), &fmt1);
                outfile2 = hts::hts_open_format(file2.as_ptr().cast(), c"wc".as_ptr(), &fmt2);
                outfile3 = hts::hts_open_format(file3.as_ptr().cast(), c"wc".as_ptr(), &fmt3);
                outfile4 = hts::hts_open_format(file4.as_ptr().cast(), c"wc".as_ptr(), &fmt4);
                if outfile1.is_null()
                    || outfile2.is_null()
                    || outfile3.is_null()
                    || outfile4.is_null()
                {
                    write!(__out, "Could not open output file\n").unwrap();
                } else {
                    in_samhdr = sam::sam_hdr_read(infile);
                    if in_samhdr.is_null() {
                        write!(__out, "Failed to read header from file!\n").unwrap();
                    } else if sam::sam_hdr_write(outfile1, in_samhdr) == -1
                        || sam::sam_hdr_write(outfile2, in_samhdr) == -1
                        || sam::sam_hdr_write(outfile3, in_samhdr) == -1
                        || sam::sam_hdr_write(outfile4, in_samhdr) == -1
                    {
                        write!(__out, "Failed to write header\n").unwrap();
                    } else {
                        let mut c = sam::sam_read1(infile, in_samhdr, bamdata);
                        while c >= 0 {
                            if sam::sam_c_4553_sam_write1(outfile1, in_samhdr, bamdata) < 0
                                || sam::sam_c_4553_sam_write1(outfile2, in_samhdr, bamdata) < 0
                                || sam::sam_c_4553_sam_write1(outfile3, in_samhdr, bamdata) < 0
                                || sam::sam_c_4553_sam_write1(outfile4, in_samhdr, bamdata) < 0
                            {
                                write!(__out, "Failed to write output data\n").unwrap();
                                break;
                            }
                            c = sam::sam_read1(infile, in_samhdr, bamdata);
                        }
                        if c == -1 {
                            ret = 0;
                        } else {
                            write!(__out, "Error in reading data\n").unwrap();
                        }
                    }
                }
            }
        }
    }

    if !in_samhdr.is_null() {
        sam::sam_hdr_destroy(in_samhdr);
    }
    if !infile.is_null() {
        hts::hts_close(infile);
    }
    if !outfile1.is_null() {
        hts::hts_close(outfile1);
    }
    if !outfile2.is_null() {
        hts::hts_close(outfile2);
    }
    if !outfile3.is_null() {
        hts::hts_close(outfile3);
    }
    if !outfile4.is_null() {
        hts::hts_close(outfile4);
    }
    if !fmt1.specific.is_null() {
        hts::hts_opt_free(fmt1.specific.cast());
    }
    if !fmt2.specific.is_null() {
        hts::hts_opt_free(fmt2.specific.cast());
    }
    if !fmt3.specific.is_null() {
        hts::hts_opt_free(fmt3.specific.cast());
    }
    if !fmt4.specific.is_null() {
        hts::hts_opt_free(fmt4.specific.cast());
    }
    if !bamdata.is_null() {
        sam::bam_destroy1(bamdata);
    }
    __out.flush().unwrap();
    ret
}
