use std::ffi::{c_char, c_int};

use crate::htslib_rs::{hts, sam};

// original: print_usage (htslib/samples/cram.c:37)
pub unsafe fn samples_cram_c_37_print_usage(fp: *mut libc::FILE) {
    libc::fprintf(
        fp,
        c"Usage: cram infile reffile outdir\nDumps the input file alignments in cram format in given directory\n1.cram has external reference\n2.cram has reference embedded\n3.cram has autogenerated reference\n4.cram has no reference data in it\n".as_ptr(),
    );
}

// original: main (htslib/samples/cram.c:53)
pub unsafe fn samples_cram_c_53_main(argc: c_int, argv: *mut *mut c_char) -> c_int {
    let mut ret = libc::EXIT_FAILURE;
    let mut infile = std::ptr::null_mut();
    let mut outfile1 = std::ptr::null_mut();
    let mut outfile2 = std::ptr::null_mut();
    let mut outfile3 = std::ptr::null_mut();
    let mut outfile4 = std::ptr::null_mut();
    let mut in_samhdr = std::ptr::null_mut();
    let mut bamdata = std::ptr::null_mut();
    let mut fmt1: hts::htsFormat = std::mem::zeroed();
    let mut fmt2: hts::htsFormat = std::mem::zeroed();
    let mut fmt3: hts::htsFormat = std::mem::zeroed();
    let mut fmt4: hts::htsFormat = std::mem::zeroed();

    if argc != 4 {
        samples_cram_c_37_print_usage(crate::htslib_rs::c_compat::stdout.cast());
        return ret;
    }
    let inname = *argv.add(1);
    let reffile = *argv.add(2);
    let outdir = *argv.add(3);

    let size1 = libc::strlen(reffile) + c"cram,reference=".to_bytes_with_nul().len() + 1;
    let size2 =
        libc::strlen(reffile) + c"cram,embed_ref=1,reference=".to_bytes_with_nul().len() + 1;
    let size3 = libc::strlen(outdir) + c"/1.cram".to_bytes_with_nul().len() + 1;
    let reffmt1 = libc::malloc(size1).cast::<c_char>();
    let reffmt2 = libc::malloc(size2).cast::<c_char>();
    let file1 = libc::malloc(size3).cast::<c_char>();
    let file2 = libc::malloc(size3).cast::<c_char>();
    let file3 = libc::malloc(size3).cast::<c_char>();
    let file4 = libc::malloc(size3).cast::<c_char>();

    if file1.is_null()
        || file2.is_null()
        || file3.is_null()
        || file4.is_null()
        || reffmt1.is_null()
        || reffmt2.is_null()
    {
        libc::printf(c"Failed to create buffers\n".as_ptr());
    } else {
        libc::snprintf(reffmt1, size1, c"cram,reference=%s".as_ptr(), reffile);
        libc::snprintf(
            reffmt2,
            size2,
            c"cram,embed_ref=1,reference=%s".as_ptr(),
            reffile,
        );
        libc::snprintf(file1, size3, c"%s/1.cram".as_ptr(), outdir);
        libc::snprintf(file2, size3, c"%s/2.cram".as_ptr(), outdir);
        libc::snprintf(file3, size3, c"%s/3.cram".as_ptr(), outdir);
        libc::snprintf(file4, size3, c"%s/4.cram".as_ptr(), outdir);

        if hts::hts_parse_format(&mut fmt1, reffmt1) == -1
            || hts::hts_parse_format(&mut fmt2, reffmt2) == -1
            || hts::hts_parse_format(&mut fmt3, c"cram,embed_ref=2".as_ptr()) == -1
            || hts::hts_parse_format(&mut fmt4, c"cram,no_ref=1".as_ptr()) == -1
        {
            libc::printf(c"Failed to set output option\n".as_ptr());
        } else {
            bamdata = sam::bam_init1();
            if bamdata.is_null() {
                libc::printf(c"Failed to initialize bamdata\n".as_ptr());
            } else {
                infile = hts::hts_open(inname, c"r".as_ptr());
                if infile.is_null() {
                    libc::printf(c"Could not open %s\n".as_ptr(), inname);
                } else {
                    outfile1 = hts::hts_open_format(file1, c"wc".as_ptr(), &fmt1);
                    outfile2 = hts::hts_open_format(file2, c"wc".as_ptr(), &fmt2);
                    outfile3 = hts::hts_open_format(file3, c"wc".as_ptr(), &fmt3);
                    outfile4 = hts::hts_open_format(file4, c"wc".as_ptr(), &fmt4);
                    if outfile1.is_null()
                        || outfile2.is_null()
                        || outfile3.is_null()
                        || outfile4.is_null()
                    {
                        libc::printf(c"Could not open output file\n".as_ptr());
                    } else {
                        in_samhdr = sam::sam_hdr_read(infile);
                        if in_samhdr.is_null() {
                            libc::printf(c"Failed to read header from file!\n".as_ptr());
                        } else if sam::sam_hdr_write(outfile1, in_samhdr) == -1
                            || sam::sam_hdr_write(outfile2, in_samhdr) == -1
                            || sam::sam_hdr_write(outfile3, in_samhdr) == -1
                            || sam::sam_hdr_write(outfile4, in_samhdr) == -1
                        {
                            libc::printf(c"Failed to write header\n".as_ptr());
                        } else {
                            let mut c = sam::sam_read1(infile, in_samhdr, bamdata);
                            while c >= 0 {
                                if sam::sam_c_4553_sam_write1(outfile1, in_samhdr, bamdata) < 0
                                    || sam::sam_c_4553_sam_write1(outfile2, in_samhdr, bamdata) < 0
                                    || sam::sam_c_4553_sam_write1(outfile3, in_samhdr, bamdata) < 0
                                    || sam::sam_c_4553_sam_write1(outfile4, in_samhdr, bamdata) < 0
                                {
                                    libc::printf(c"Failed to write output data\n".as_ptr());
                                    break;
                                }
                                c = sam::sam_read1(infile, in_samhdr, bamdata);
                            }
                            if c == -1 {
                                ret = libc::EXIT_SUCCESS;
                            } else {
                                libc::printf(c"Error in reading data\n".as_ptr());
                            }
                        }
                    }
                }
            }
        }
    }

    if !in_samhdr.is_null() {
        sam::sam_hdr_destroy(in_samhdr);
    }
    if !infile.is_null() {
        hts::hts_close(infile);
    }
    if !outfile1.is_null() {
        hts::hts_close(outfile1);
    }
    if !outfile2.is_null() {
        hts::hts_close(outfile2);
    }
    if !outfile3.is_null() {
        hts::hts_close(outfile3);
    }
    if !outfile4.is_null() {
        hts::hts_close(outfile4);
    }
    if !file1.is_null() {
        libc::free(file1.cast());
    }
    if !file2.is_null() {
        libc::free(file2.cast());
    }
    if !file3.is_null() {
        libc::free(file3.cast());
    }
    if !file4.is_null() {
        libc::free(file4.cast());
    }
    if !reffmt1.is_null() {
        libc::free(reffmt1.cast());
    }
    if !reffmt2.is_null() {
        libc::free(reffmt2.cast());
    }
    if !fmt1.specific.is_null() {
        hts::hts_opt_free(fmt1.specific.cast());
    }
    if !fmt2.specific.is_null() {
        hts::hts_opt_free(fmt2.specific.cast());
    }
    if !fmt3.specific.is_null() {
        hts::hts_opt_free(fmt3.specific.cast());
    }
    if !fmt4.specific.is_null() {
        hts::hts_opt_free(fmt4.specific.cast());
    }
    if !bamdata.is_null() {
        sam::bam_destroy1(bamdata);
    }
    ret
}
